name: example ci/cd

on:
  push:
    branches: [ main, master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: installing env
        run: pip install flask pytest
      - name: testing
        working-directory: ./gamedev
        run: pytest
